---
title: ""
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
set_palette(
  qualitative = c(
    "orange3",
    "red3",
    "navy",
    "steelblue"
  ),
  binary = c("orange3", "navy"),
  sequential = c("skyblue1", "navy"),
  diverging = c("orange3", "white", "navy")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 4, wd = 6) {
  ggsave(
    here::here(
      "025_whats_in_gdp",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data

```{r}
dt <- read_csv(
  here::here(
    "_data", "GMD.csv"
  )
)

dt |>
  filter(
    ISO3 == "USA",
    year < 2025 # how is this in here?
  ) |>
  transmute(
    year,
    c = cons,
    i = inv,
    g = govexp,
    x = exports,
    m = imports,
    y = c + i + g + (x - m)
  ) |>
  drop_na() -> dt

## adjust for inflation
library(priceR)
inf_dt <- retrieve_inflation_data("US")
cty_dt <- show_countries()
dt |>
  mutate(
    across(
      c:y,
      ~ adjust_for_inflation(
        .x, year, "US", 2023,
        inflation_dataframe = inf_dt,
        countries_dataframe = cty_dt
      )
    )
  ) -> dt
```


## Figures

```{r}
#| fig-height: 5
#| fig-width: 6

ggplot(dt) +
  aes(year, y) +
  geom_line(
    color = "orange3",
    linewidth = 1
  ) +
  labs(
    title = str_wrap(
      "U.S. GDP over time, 1960-2024",
      width = 37
    ),
    subtitle = str_wrap(
      "Based on summing 2023 constant consumption, investment, government expentidures, and net exports. Inflation adjustment done with {priceR}. Data source: Global Macro Database (globalmacrodata.com)",
      width = 60
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1960, 2025, by = 5)
  ) +
  scale_y_continuous(
    labels = ~ paste0(
      "$", .x / 1e06, 
      " tril"
    )
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  )
saveit(1, 5)
```


```{r}
#| fig-height: 5
#| fig-width: 6

dt |>
  mutate(
    nx = x - m
  ) |>
  pivot_longer(
    c(c, i, g, nx)
  ) |>
  mutate(
    name = rep(
      c("Consumption",
        "Investment",
        "Gov't Expenditure",
        "Net Exports"),
      len = n()
    )
  ) |>
  ggplot() +
  aes(year, value) +
  geom_textline(
    aes(color = name, label = name),
    linewidth = 1,
    text_smoothing = 50,
    show.legend = F,
    family = "mono",
    fontface = "bold.italic"
  ) +
  labs(
    title = str_wrap(
      "U.S. GDP components, 1960-2024",
      width = 37
    ),
    subtitle = str_wrap(
      "Based on 2023 constant consumption, investment, government expentidures, and net exports. Inflation adjustment done with {priceR}. Data source: Global Macro Database (globalmacrodata.com)",
      width = 60
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1960, 2025, by = 5)
  ) +
  scale_y_continuous(
    labels = ~ paste0(
      "$", .x / 1e06, 
      " tril"
    )
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  ) +
  ggpal()
saveit(2, 5)
```


```{r}
#| fig-height: 5
#| fig-width: 6

dt |>
  mutate(
    nx = x - m
  ) |>
  pivot_longer(
    c(c, i, g, nx)
  ) |>
  mutate(
    name = rep(
      c("Consumption",
        "Investment",
        "Gov't Expenditure",
        "Net Exports"),
      len = n()
    ),
    value = value / y
  ) |>
  ggplot() +
  aes(year, value) +
  geom_textline(
    aes(color = name, label = name),
    linewidth = 1,
    text_smoothing = 50,
    show.legend = F,
    family = "mono",
    fontface = "bold.italic"
  ) +
  labs(
    title = str_wrap(
      "U.S. GDP component shares, 1960-2024",
      width = 37
    ),
    subtitle = str_wrap(
      "Based on 2023 constant consumption, investment, government expentidures, and net exports. Inflation adjustment done with {priceR}. Data source: Global Macro Database (globalmacrodata.com)",
      width = 60
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1960, 2025, by = 5)
  ) +
  scale_y_continuous(
    labels = scales::percent,
    breaks = seq(0, 1, by = .1)
  ) +
  theme(
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    )
  ) +
  ggpal()
saveit(3, 5)
```


GDP growth per gov't expenditure growth.

```{r}
pdiff <- function(x1, x0) {
  (x1 - x0) / x1
}
dt |>
  mutate(
    ydiff = pdiff(
      y, lag(y, order_by = year)
    ),
    gdiff = pdiff(
      y - g, lag(y - g, order_by = year)
    ),
    rat = ydiff - gdiff
  ) |>
  mean_ci(rat)
```

