---
title: "Doodles"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
set_palette(
  qualitative = c(
    "orange3",
    "gray40",
    "navy"
  ),
  binary = c("orange3", "navy"),
  diverging = c("orange3", "white", "navy"),
  sequential = c("white", "navy")
)
source(here::here("my_theme.R"))
saveit <- function(file, ht = 4, wd = 6) {
  ggsave(
    here::here(
      "_doodle_figs",
      paste0(file, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```

## U.S. trade leverage over Canada

Get some data:

```{r}
library(peacesciencer)
create_dyadyears() |>
  add_cow_trade() |>
  add_sdp_gdp() -> dt

## whittle down to Canada bilateral trade in 2014
dt |>
  filter(ccode1 == 20, year == 2014) |>
  drop_na() -> dt

## Clean up the data a bit
dt |>
  transmute(
    partner = countrycode::countrycode(
      ccode2, "cown", "country.name"
    ),
    trade = flow1 + flow2,
    gdp = exp(wbgdp2011est1) / 1e06
  ) -> dt

## adjust gdp for inflation
library(priceR)
inf_dt <- retrieve_inflation_data("US")
cty_dt <- show_countries()

dt |>
  mutate(
    gdp2014 = adjust_for_inflation(
        gdp, 2011, "US", 2014,
        inflation_dataframe = inf_dt,
        countries_dataframe = cty_dt
      ) |> round()
  ) -> dt
```

Make a data viz:

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  mutate(
    leverage = trade / gdp2014
  ) |>
  slice_max(leverage, n = 5) |>
  ggplot() +
  aes(x = leverage, y = reorder(partner, leverage)) +
  geom_col(
    fill = "navy"
  ) +
  my_theme() +
  labs(
    title = str_wrap(
      "Canada's top trading partners per GDP",
      width = 37
    ),
    subtitle = str_wrap(
      "Data accessed with the {peacesciencer} R package. Values shown for 2014.",
      width = 50
    ),
    x = "Trade per GDP (%)",
    y = NULL,
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(0, .4, by = .05),
    labels = scales::percent
  )
saveit("leverage_over_canada.png")
```


## U.S. military aid vs foreign aid

```{r}
## the data
dt <- read_csv(
  here::here(
    "_data",
    "us_foreign_aid_ukraine.csv"
  )
)

dt <- dt |>
  janitor::clean_names() 

dt |>
  filter(
    fiscal_year >= 2020
  ) |>
  mutate(
    org = frcode(
      managing_agency_acronym == "USAID" ~
        "USAID",
      managing_agency_acronym == "DOD" ~ 
        "DOD",
      TRUE ~ "Other"
    )
  ) |>
  group_by(
    fiscal_year,
    org
  ) |>
  summarize(
    aid = sum(constant_dollar_amount)
  ) |>
  ungroup() -> dt
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  ggplot() +
  aes(
    x = fiscal_year,
    y = aid,
    color = org
  ) +
  geom_line(
    linewidth = 1
  ) +
  geom_point(
    pch = 21,
    fill = "white"
  ) +
  my_theme() +
  scale_y_continuous(
    labels = ~ paste0(
      scales::dollar(.x / 1e09),
      " bil"
    )
  ) +
  ggpal() +
  labs(
    title = 
      "USAID manages the largest portfolio\nof aid to Ukraine compared to the DOD\nand other agencies",
    subtitle = 
      "Billions of 2024 constant dollars shown, 2020-2024",
    caption = logo,
    color = NULL
  )
saveit(
  "ukraine_aid_by_agency"
)
```


## U.S troops in Greenland

```{r}
library(troopdata)

troops <- get_troopdata(
  host = "Greenland",
  branch = T,
  guard_reserve = T,
  civilians = T
)
```

```{r}
#| fig-height: 4
#| fig-width: 6

ggplot(troops) +
  aes(
    x = year,
    y = troops_ad
  ) +
  geom_line(
    linewidth = 1,
    color = "orange3"
  ) +
  ggrepel::geom_text_repel(
    data = . %>%
      filter(troops_ad == max(troops_ad)),
    aes(label = scales::comma(troops_ad)),
    nudge_x = 15,
    color = "navy",
    family = "mono",
    fontface = "bold"
  ) +
  ggrepel::geom_text_repel(
    data = . %>%
      filter(year == 2024),
    aes(label = scales::comma(troops_ad)),
    nudge_y = 1000,
    nudge_x = -10,
    color = "navy",
    family = "mono",
    fontface = "bold"
  ) +
  my_theme() +
  labs(
    title = 
      "Greenland has hosted U.S. troops\nfor a long time",
    subtitle = 
      "Total U.S. troops stationed in Greenland, 1950-2024",
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1950, 2020, by = 10)
  ) +
  scale_y_continuous(
    labels = scales::comma
  )
saveit(
  "greenland_troops"
)
```


## U.S. Foreign Aid

```{r}
#| fig-height: 4
#| fig-width: 6

## Data:
dt <- read_csv(
  here::here("_data", "us_foreign_aid_country.csv")
)

dt |>
  janitor::clean_names() |>
  filter(
    transaction_type_name ==
      "Disbursements"
  ) |>
  group_by(fiscal_year) |>
  summarize(
    aid = sum(constant_amount)
  ) |>
  ggplot() +
  aes(x = as.numeric(fiscal_year), y = aid) +
  geom_line(
    color = "navy"
  ) +
  geom_point(color = "orange3") +
  my_theme() +
  labs(
    title = 
      "U.S. Aid Giving Since 2001",
    subtitle = 
      "U.S. aid disbursements in billions of constant $",
    caption = logo
  ) +
  scale_y_continuous(
    labels = ~ scales::dollar(.x / 1e09)
  )
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  janitor::clean_names() |>
  filter(
    transaction_type_name ==
      "Disbursements",
    country_name == "Ukraine"
  ) |>
  ggplot() +
  aes(x = as.numeric(fiscal_year), y = constant_amount) +
  geom_line(
    color = "navy"
  ) +
  geom_point(color = "orange3") +
  my_theme() +
  labs(
    title = 
      "U.S. Aid Giving to Ukraine Since 2001",
    subtitle = 
      "U.S. aid disbursements in billions of constant $",
    caption = logo
  ) +
  scale_y_continuous(
    labels = ~ scales::dollar(.x / 1e09)
  )
saveit(
  "us_aid_ukraine"
)
```


```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  janitor::clean_names() |>
  filter(
    transaction_type_name ==
      "Disbursements"
  ) |>
  group_by(fiscal_year) |>
  summarize(
    aid = sum(constant_amount),
    ukr = sum(constant_amount[country_name == "Ukraine"]),
    share = ukr / aid
  ) |>
  ggplot() +
  aes(x = as.numeric(fiscal_year), y = share) +
  geom_line(
    color = "navy"
  ) +
  geom_point(color = "orange3") +
  my_theme() +
  labs(
    title = 
      "U.S. Aid Giving to Ukraine Since 2001",
    subtitle = 
      "Share of U.S. aid dispursements going to Ukraine",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  )
```


## Int'l Conflict Rate over Time

```{r}
#| fig-height: 4
#| fig-width: 6
## data:
ucdp <- read_csv(
  here::here(
    "_data", "UcdpPrioConflict_v24_1.csv"
  )
)

ucdp |>
  group_by(year) |>
  count(type_of_conflict) |>
  mutate(
    type_of_conflict = 
      frcode(
        type_of_conflict == 1 ~ "Extrasystemic",
        type_of_conflict == 2 ~ "Interstate",
        type_of_conflict == 3 ~ "Intrastate",
        type_of_conflict == 4 ~ "Internationalized\nIntrastate"
      )
  ) |>
  ggplot() +
  aes(x = year, y = n) +
  geom_line(
    aes(color = type_of_conflict)
  ) +
  labs(
    title = 
      "Conflict frequencies by year from UCDP",
    subtitle = 
      "Count of conflicts that kill at least 25 per year\nby type, 1946-2022",
    color = NULL,
    caption = logo
  ) +
  my_theme() 
saveit("ucdp_conf_types")
```



## U.S. Trade Centrality

```{r}
#| fig-height: 4
#| fig-width: 6

## trade data
library(peacesciencer)
create_stateyears(
  subset_years = 1920:2014
) |>
  add_cow_trade() -> dt

## Note: flow1 = imports to 1 and flow2 is exports to 2

dt |>
  group_by(year) |>
  summarize(
    total = sum(exports, na.rm = T),
    us_share = sum(
      exports[ccode == 2], na.rm = T
    ) / total,
    ch_share = sum(
      exports[ccode == 710]
    ) / total
  ) |>
  ggplot() +
  aes(x = year) +
  geom_textsmooth(
    aes(y = us_share),
    label = "United States",
    method = "gam",
    se = F,
    color = "navy",
    hjust = .7,
    linewidth = 1
  ) +
  geom_textsmooth(
    aes(y = ch_share),
    label = "China",
    method = "gam",
    se = F,
    color = "orange3",
    hjust = .7,
    linewidth = 1
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  scale_x_continuous(
    breaks = seq(1920, 2010, by = 10)
  ) +
  my_theme() +
  labs(
    title = 
      "China leads U.S. in global exports",
    subtitle = 
      "(%) share of global exports, 1920-2014",
    caption = logo
  ) +
  annotate(
    "text",
    x = 1990,
    y = .25,
    label = "Smoothed average trends\nestimated with a\ngeneralized additive model",
    family = "mono",
    fontface = "bold"
  )
saveit("china_v_us_trade_share")
```

