---
title: "Democratic Backsliding"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
set_palette(
  qualitative = c(
    "orange3",
    "gray80",
    "navy",
    "steelblue"
  ),
  binary = c("orange3", "navy"),
  sequential = c("white", "navy"),
  diverging = c("orange3", "white", "navy")
)
source(here::here("my_theme.R"))
saveit <- function(num = 1, ht = 4, wd = 6) {
  ggsave(
    here::here(
      "021_dem_backslide",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data

```{r}
library(democracyData)
generate_democracy_scores_dataset(
  datasets = c("vdem", "polity"),
  verbose = F
) -> dt

dt |>
  drop_na() |>
  filter(
    measure %in% c(
      "v2x_polyarchy",
      "polity2"
    )
  )-> fdt
```


## Figures

```{r}
#| fig-height: 4
#| fig-width: 6
rs <- function(x) {
  x <- x - min(x, na.rm = T)
  x <- x / max(x, na.rm = T)
  x
}
fdt |>
  group_by(measure) |>
  mutate(
    svalue = rs(value)
  ) |>
  filter(cown == 2) |>
  ggplot() +
  aes(year, svalue, color = measure) +
  geom_line() +
  ggpal(
    "binary",
    labels = c("Polity 2", "V-Dem")
  ) +
  my_theme() +
  labs(
    title = str_wrap(
      "Not all democracy measures tell a consistent story across time",
      width = 37
    ),
    subtitle = str_wrap(
      "Comparison of Polity 2 and V-Dem measures of quality of democracy in the U.S.",
      width = 50
    ),
    x = NULL,
    y = NULL,
    color = NULL,
    caption = logo
  ) +
  scale_y_continuous(
    breaks = 0:1,
    labels = c(
      "Lowest\nScore\n",
      "\nHighest\nScore"
    ),
    limits = 0:1
  ) +
  scale_x_continuous(
    breaks = seq(1780, 2020, by = 20)
  ) +
  theme(
    panel.grid.major.x = 
      element_blank(),
    axis.text.x = element_text(
      angle = 45,
      hjust = 1
    ),
    legend.position = c(.9, .25),
    legend.direction = "vertical"
  )
saveit(1)
```



