---
title: "Untitled"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(ggrepel)
library(coolorrr)
library(here)
set_palette(
  qualitative = c(
    "steelblue",
    "navy",
    "red3",
    "orange3"
  ),
  binary = c("navy", "orange"),
  sequential = c("white", "steelblue"),
  diverging = c("red3", "white", "navy")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 5, wd = 6) {
  ggsave(
    here(
      "060_us_bases_2",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```



## Data

```{r}
dt <- read_csv(
  here::here(
    "_data",
    "apsr-data-outside-the-wire.csv"
  )
)
```


```{r}
library(troopdata)
td <- get_troopdata(
  startyear = 2018,
  endyear = 2019
)

td |>
  transmute(
    ccode, year, troops_ad
  ) -> td
```

```{r}
library(globalmacrodata)

gm <- gmd()
gm |>
  transmute(
    ccode = countrycode::countrycode(
      countryname, "country.name", "cown"
    ),
    year, pop
  ) -> gm


```



```{r}
dt |>
  mutate(
    ccode = countrycode::countrycode(
      country, "country.name", "cown"
    )
  )-> dt

dt |>
  left_join(
    td |> filter(year == 2019),
    by = c("ccode")
  ) |>
  left_join(
    gm |> filter(year == 2019),
    by = c("ccode")
  )-> dt
```

## Figures

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  mutate(
    contact = ifelse(contact_pers == "Yes", 1, 0)
  ) -> dt

dt |>
  group_by(country) |>
  summarize(
    contact = mean(contact, na.rm = T),
    troops = unique(troops_ad / pop),
    .groups = "drop"
  ) |>
  drop_na() |>
  ggplot() +
  aes(troops, contact) +
  geom_point(
    color = "orange"
  ) +
  geom_smooth(
    method = "lm",
    formula = y ~ x,
    se = F,
    color = "navy"
  )  +
  labs(
    title = str_wrap(
      "More U.S. troops...more contact",
      width = 37
    ),
    subtitle = str_wrap(
      "Source: Allen, Flynn, Machain, & Stravers (2020) APSR + {troopdata}.",
      width = 55
    ),
    x = "Troops per 1 million",
    y = "% Contact",
    caption = logo
  ) +
  scale_y_continuous(
    labels = percent
  )
saveit(1, 4)
```

```{r}
dt |>
  group_by(country) |>
  summarize(
    contact = mean(contact, na.rm = T) * 100,
    troops = unique(troops_ad / (pop)) / 100
  ) |>
  drop_na() |>
  lm(contact ~ troops, data = _)
```

```{r}
dt |>
  mutate(
    across(
      c(troops_1, american_gov:american_people),
      ~ ifelse(
        .x %in% c("Somewhat favorable", "Very favorable"),
        1, 0
      ),
      .names = "{col}_rec"
    ),
    any_influence = ifelse(
      american_inf_1 %in% c("Some", "A little", "A lot"), 1, 0
    ),
    pos_influence = ifelse(
      american_inf_2 %in% c("Positive", "Very positive"),
      1, 0
    )
  ) -> dt
```


```{r}
library(mfx)

tibble(
  model = c("Positive assessment of U.S. troops", 
            "Positive assessment of U.S. gov't",
            "Positive assessment of U.S. people",
            "Seeing the U.S. as influential",
            "Seeing U.S. influence as positive"),
  form = list(
    troops_1_rec ~ contact,
    american_gov_rec ~ contact,
    american_people_rec ~ contact,
    any_influence ~ contact,
    pos_influence ~ contact
  ),
  fit  = map(
    form,
    ~ logitmfx(
        update(.x, . ~ . + 
                 gender + minority + ed + age + income + country), 
        data = dt,
        robust = T
      )
  )
) -> mod_ests

mod_ests |>
  mutate(
    coef = map(fit, ~ tidy(.x) |> filter(term == "contact"))
  ) |>
  unnest(
    coef
  ) -> mod_ests
```


```{r}
#| fig-height: 5
#| fig-width: 6

mod_ests |>
  mutate(
    lo = estimate - 1.96 * std.error,
    hi = estimate + 1.96 * std.error,
    ord = 1:n()
  ) |>
  ggplot() +
  aes(
    x = estimate * 100,
    y = reorder(str_wrap(model, 15), - ord),
    xmin = lo * 100,
    xmax = hi * 100
  ) +
  geom_pointrange(
    color = "navy"
  ) +
  geom_vline(
    xintercept = 0,
    color = "orange"
  ) +
  geom_text(
    aes(label = paste0("+ ", round(estimate * 100, 1), "%")),
    vjust = -1,
    family = "mono",
    fontface = "bold",
    color = "navy"
  ) +
  scale_x_continuous(
    breaks = 0
  ) +
  labs(
    title = str_wrap(
      "Contact with U.S. troops reflects well on America",
      width = 37
    ),
    subtitle = str_wrap(
      "Predicted change in the likelihood of...",
      width = 55
    ),
    x = "Percentage point change due to\ncontact with U.S. troops",
    y = NULL,
    caption = logo
  ) +
  geom_label(
    x = .1,
    y = 5,
    label = str_wrap(
      "Predictions based on logit models, controlling for gender, minority status, education, age, income, survey year, and country.",
      width = 45
    ),
    hjust = 0,
    family = "mono",
    fontface = "bold",
    size = 3
  )
saveit(2)
```



```{r}
mod_outs <- list()
countries <- unique(dt$country) |> na.omit()
for(i in 1:14) {
  expand_grid(
    model = c("Positive assessment of U.S. troops", 
              "Positive assessment of U.S. gov't",
              "Positive assessment of U.S. people",
              "Seeing the U.S. as influential",
              "Seeing U.S. influence as positive"),
    form = list(
      troops_1_rec ~ contact,
      american_gov_rec ~ contact,
      american_people_rec ~ contact,
      any_influence ~ contact,
      pos_influence ~ contact
    ),
    fit  = map(
      form,
      ~ logitmfx(
          update(.x, . ~ . + 
                   gender + minority + ed + age + income), 
          data = dt |> filter(country == countries[i]),
          robust = T
        )
    )
  ) -> mod_estsi
  
  mod_estsi |>
    mutate(
      coef = map(fit, ~ tidy(.x) |> filter(term == "contact")),
      country = countries[i]
    ) |>
    unnest(
      coef
    ) -> mod_outs[[i]]
}

mod_outs |>
  bind_rows() 
```

