---
title: "Monroe Doctrine"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(ggrepel)
library(coolorrr)
library(here)
set_palette(
  qualitative = c(
    "steelblue",
    "navy",
    "red3",
    "orange3"
  ),
  binary = c("navy", "orange"),
  sequential = c("white", "steelblue"),
  diverging = c("red3", "white", "navy")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 5, wd = 6) {
  ggsave(
    here(
      "066_monroe",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data

```{r}
library(peacesciencer)

create_dyadyears("gw", subset_years = 1946:2024) -> dt

  bind_rows(
    ucdp_acd |>
      transmute(
        gwcode1 = gwno_a,
        gwcode2 = gwno_b,
        year,
        intensity_level
      ) |>
      group_by(gwcode1, gwcode2, year) |>
      summarize(
        ac = 1,
        maxintensity = max(intensity_level)
      ),
    ucdp_acd |> 
      transmute(
        gwcode1 = gwno_a_2nd,
        gwcode2 = gwno_b_2nd,
        year,
        intensity_level
      ) |>
      group_by(gwcode1, gwcode2, year) |>
      summarize(
        ac = 1,
        maxintensity = max(intensity_level)
      ),
    ucdp_acd |> 
      transmute(
        gwcode1 = gwno_a,
        gwcode2 = gwno_b_2nd,
        year,
        intensity_level
      ) |>
      group_by(gwcode1, gwcode2, year) |>
      summarize(
        ac = 1,
        maxintensity = max(intensity_level)
      ),
    ucdp_acd |> 
      transmute(
        gwcode1 = gwno_a_2nd,
        gwcode2 = gwno_b,
        year,
        intensity_level
      ) |>
      group_by(gwcode1, gwcode2, year) |>
      summarize(
        ac = 1,
        maxintensity = max(intensity_level)
      )
  ) |> drop_na() -> ft
  
dt |>
  left_join(
    ft
  ) |>
  mutate(
    ac = replace_na(ac, 0)
  ) -> dt
```


```{r}
create_stateyears(
  "gw", subset_years = 1946:2024
) -> dt

bind_rows(
  ucdp_acd |>
    transmute(
      gwcode = gwno_a,
      year,
      conflict_id,
      intensity_level,
      type_of_conflict
    ) |>
    group_by(gwcode, year, conflict_id) |>
    mutate(
      init = (row_number() == 1) + 0
    ) |>
    ungroup(),
  ucdp_acd |>
    transmute(
      gwcode = gwno_a_2nd,
      year,
      conflict_id,
      intensity_level,
      type_of_conflict,
      init = 0
    ),
  ucdp_acd |>
    transmute(
      gwcode = gwno_b,
      year,
      conflict_id,
      intensity_level,
      type_of_conflict,
      init = 0
    ),
  ucdp_acd |>
    transmute(
      gwcode = gwno_b_2nd,
      year,
      conflict_id,
      intensity_level,
      type_of_conflict,
      init = 0
    )
) |>
  drop_na(gwcode) |>
  group_by(gwcode, year) |>
  summarize(
    total = length(unique(conflict_id)),
    wars  = length(unique(conflict_id[intensity_level == 2])),
    init  = length(unique(conflict_id[init == 1]))
  ) -> ft

dt |>
  left_join(ft) -> dt

dt |>
  mutate(
    across(c(total:wars, init), ~ replace_na(.x, 0))
  ) -> dt
```




## Figures

```{r}
#| fig-height: 5
#| fig-width: 6

dt |>
  filter(gwcode == 2) |>
  ggplot() +
  aes(year, total) +
  geom_point(color = "navy") +
  geom_line(color = "navy") +
  geom_ribbon(
    data = . %>%
      filter(year %in% 2017:2021),
    aes(
      ymax = Inf,
      ymin = -Inf
    ),
    alpha = 0.4
  ) +
  labs(
    title = str_wrap(
      "The U.S. was involved in more armed conflicts during Trump 1.0 than at any other time since WWII",
      width = 37
    ),
    subtitle = str_wrap(
      "Source: UCDP-ACD via {peacesciencer}"
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  geom_text(
    x = 2000,
    y = 5,
    label = "# of U.S.\nconflicts",
    color = "navy",
    family = "mono",
    fontface = "bold"
  )
saveit(1)
```


```{r}
#| fig-height: 5
#| fig-width: 6

dt |>
  filter(gwcode == 2) |>
  ggplot() +
  aes(year, wars) +
  geom_point(color = "navy") +
  geom_line(color = "navy") +
  geom_ribbon(
    data = . %>%
      filter(year %in% 2017:2021),
    aes(
      ymax = Inf,
      ymin = -Inf
    ),
    alpha = 0.4
  ) +
  labs(
    title = str_wrap(
      "U.S. involvement in wars (> 1,000 battle deaths) declined during Trump 1.0 after a historic peak at the end of Obama's presidency",
      width = 37
    ),
    subtitle = str_wrap(
      "Source: UCDP-ACD via {peacesciencer}"
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  geom_text(
    x = 2000,
    y = 3.5,
    label = "# of wars with\nU.S. involvement",
    color = "navy",
    family = "mono",
    fontface = "bold"
  )
saveit(2)
```

```{r}
#| fig-height: 5
#| fig-width: 6

ucdp_acd |>
  group_by(year) |>
  summarize(
    total = length(unique(conflict_id))
  ) |>
  ggplot() +
  aes(year, total) +
  geom_point(color = "navy") +
  geom_line(color = "navy") +
  labs(
    title = str_wrap(
      "The number of armed conflicts in the world has reached historic hights",
      width = 37
    ),
    subtitle = str_wrap(
      "Source: UCDP-ACD via {peacesciencer}"
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  geom_text(
    x = 1980,
    y = 55,
    label = "# of ongoing\narmed conflicts",
    color = "navy",
    family = "mono",
    fontface = "bold"
  )
saveit(3)
```


```{r}
#| fig-height: 5
#| fig-width: 6

dt |>
  group_by(year) |>
  summarize(
    total = sum(total > 0)
  ) |>
  ggplot() +
  aes(year, total) +
  geom_point(color = "navy") +
  geom_line(color = "navy") +
  labs(
    title = str_wrap(
      "The number of countries involved in armed conflicts has been increasing substantially",
      width = 37
    ),
    subtitle = str_wrap(
      "Source: UCDP-ACD via {peacesciencer}"
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  geom_text(
    x = 1980,
    y = 95,
    label = "# of countries\ninvolved in conflicts",
    color = "navy",
    family = "mono",
    fontface = "bold"
  )
saveit(4)
```



