---
title: "More conflicts than ever?"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(ggrepel)
library(coolorrr)
library(here)
set_palette(
  qualitative = c(
    "steelblue",
    "navy",
    "red3",
    "orange3"
  ),
  binary = c("orange", "navy"),
  sequential = c("white", "steelblue"),
  diverging = c("red3", "white", "navy")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 5, wd = 6) {
  ggsave(
    here(
      "072_conflict_over_time",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```

## Data

```{r}
library(tidyverse)
library(peacesciencer)
```

```{r}
## no. of interstate conflicts from ACD
ucdp_acd |>
  filter(type_of_conflict == "interstate") |>
  group_by(year) |>
  summarize(
    acd = n_distinct(conflict_id)
  ) -> yearly_acd

## no. of mics from MIC dataset
read_csv(
  here("_data", "mic-conf-1.0.csv")
) -> mics
tibble(
  micnum = c(mics$micnum, mics$micnum),
  year = c(mics$styear, mics$endyear),
  fatalmin = c(mics$fatalmin, mics$fatalmin),
  fatalmax = c(mics$fatalmax, mics$fatalmax)
) |>
  arrange(micnum) |>
  distinct() |>
  group_by(micnum) |>
  complete(
    year = full_seq(year, 1)
  ) |>
  mutate(
    across(
      everything(),
      ~ max(.x, na.rm = T)
    )
  ) |>
  group_by(year) |>
  summarize(
    mics = n_distinct(micnum),
    mics25min = n_distinct(micnum[fatalmin >= 25], na.rm = T),
    mics25max = n_distinct(micnum[fatalmax >= 25], na.rm = T)
  ) |>
  ungroup() -> yearly_mics

tibble(
  year = 1816:2014
) |>
  left_join(yearly_mics) |>
  mutate(
    across(
      everything(),
      ~ replace_na(.x, 0)
    )
  ) -> yearly_mics

tibble(
  year = 1946:2024
) |>
  left_join(
    yearly_acd
  ) |>
  mutate(
    acd = replace_na(acd, 0)
  ) -> yearly_acd

## merge together
full_join(
  yearly_mics,
  yearly_acd
) -> dt
```


```{r}
## now get a measure of political relevance
create_dyadyears(
  subset_years = 1816:2024,
  directed = F
) |>
  add_contiguity() |>
  add_cow_majors() -> dyadic_dt

dyadic_dt |>
  mutate(
    prd = ifelse(
      pmax(cowmaj1, cowmaj2) == 1 |
        conttype > 0,
      1, 0
    )
  ) |>
  group_by(year) |>
  summarize(
    dyads = n(),
    prdyads = sum(prd)
  ) |>
  mutate(
    prdyads = replace_na(
      prdyads, prdyads[year == 2016]
    )
  ) -> rel_dt

## merge it in
left_join(
  dt,
  rel_dt
) -> dt
```

```{r}
## now I need a measure of dyads in disputes
source(
  here("_helpers", "peacesciencer_extras.R")
)
create_dyadyears(
  subset_years = 1816:2014,
  directed = F
) |>
  add_gml_mic(fat = 25, fatmax = F) |>
  group_by(year) |>
  summarize(
    dyadic_mics25 = sum(gml_mic_ongoing)
  ) -> yearly_dyad_mics25

create_dyadyears(
  subset_years = 1816:2014,
  directed = F
) |>
  add_gml_mic() |>
  group_by(year) |>
  summarize(
    dyadic_mics0 = sum(gml_mic_ongoing)
  ) -> yearly_dyad_mics0

create_dyadyears(
  subset_years = 1816:2014,
  directed = F
) |>
  add_gml_mic(level = 4) |>
  group_by(year) |>
  summarize(
    dyadic_mics4 = sum(gml_mic_ongoing)
  ) -> yearly_dyad_mics4

create_dyadyears(
  subset_years = 1946:2024,
  directed = F,
  system = "gw"
) |>
  add_ucdp_acd_new(type = "interstate") |>
  group_by(year) |>
  summarize(
    dyadic_acds = sum(ucdp_ongoing)
  ) -> yearly_dyad_acds

## merge in
list(dt, yearly_dyad_mics0, yearly_dyad_mics25, 
     yearly_dyad_mics4, yearly_dyad_acds) |>
  reduce(left_join) -> dt
```


## Figures

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  drop_na(mics) |>
  ggplot() +
  aes(year, mics) +
  geom_line(
    color = "navy"
  ) +
  stat_smooth(
    color = "orange",
    method = "gam",
    method.args = list(family = quasipoisson)
  ) +
  labs(
    title = str_wrap(
      "The # of ongoing international conflicts per year steadily increased from 1816 to 2014",
      width = 37
    ),
    subtitle = "Source: Militarized Interstate Confrontations Dataset",
    x = NULL,
    y = "# of MICs",
    caption = logo
  )
saveit(1, 4, 6)
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  drop_na(mics) |>
  ggplot() +
  aes(year, mics / prdyads) +
  geom_line(
    color = "navy"
  ) +
  stat_smooth(
    color = "orange",
    method = "gam",
    method.args = list(family = quasibinomial)
  ) +
  labs(
    title = str_wrap(
      "The conflict rate per relevant dyad increased (but only slightly) from 1816 to 2014",
      width = 37
    ),
    subtitle = "Source: Militarized Interstate Confrontations Dataset",
    x = NULL,
    y = "MIC % Rate",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  )
saveit(2, 4, 6)
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  drop_na(mics) |>
  ggplot() +
  aes(year, dyadic_mics0 / prdyads) +
  geom_line(
    color = "navy"
  ) +
  stat_smooth(
    color = "orange",
    method = "gam",
    method.args = list(quasibinomial)
  ) +
  labs(
    title = str_wrap(
      "The dyadic conflict rate per relevant dyad shows more movement from 1816 to 2014",
      width = 37
    ),
    subtitle = "Source: Militarized Interstate Confrontations Dataset",
    x = NULL,
    y = "MIC % Rate",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  )
saveit(3, 4, 6)
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  drop_na(mics) |>
  ggplot() +
  aes(year, dyadic_mics25 / prdyads) +
  geom_line(
    color = "navy"
  ) +
  stat_smooth(
    color = "orange",
    method = "gam",
    method.args = list(family = quasibinomial)
  ) +
  labs(
    title = str_wrap(
      "A post WWII decline is more obvious when using a 25+ battle death threshold",
      width = 37
    ),
    subtitle = "Source: Militarized Interstate Confrontations Dataset",
    x = NULL,
    y = "MIC % Rate",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  )
saveit(4, 4, 6)
```

```{r}
#| fig-height: 5.5
#| fig-width: 6

dt |>
  #drop_na(acd) |>
  filter(year > 1945) |>
  ggplot() +
  aes(year) +
  geom_line(
    aes(
      y = dyadic_mics25 / prdyads,
      color = "MIC"
    )
  ) +
   geom_line(
    aes(y = dyadic_acds / prdyads, color = "ACD")
  ) +
  stat_smooth(
    aes(
      y = dyadic_mics25 / prdyads,
      color = "MIC"
    ),
    method = "gam",
    method.args = list(family = quasibinomial),
    se = F
  ) +
  stat_smooth(
    aes(y = dyadic_acds / prdyads, color = "ACD"),
    method = "gam",
    method.args = list(family = quasibinomial),
    se = F
  ) +
  geom_text_repel(
    data = . %>%
      filter(year == 2020),
    aes(y = acd / prdyads),
    label = str_wrap(
      "The trend moves upward just a bit from 2014-2024",
      width = 15
    ),
    nudge_x = 0,
    nudge_y = .05,
    family = "mono",
    fontface = "bold.italic"
  ) +
  labs(
    title = str_wrap(
      "Little evidence of a resurgence in conflict when extending the data to 2024",
      width = 37
    ),
    subtitle = "Sources: Militarized Interstate Confrontations Dataset\n& the UCDP/PRIO Armed Conflict Dataset",
    x = NULL,
    y = "% Rate",
    caption = logo,
    color = "Dataset:"
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  ggpal("binary")
saveit(5, 5.5, 6)
```


```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  drop_na(mics) |>
  ggplot() +
  aes(year, dyadic_mics4 / prdyads) +
  geom_line(
    color = "navy"
  ) +
  stat_smooth(
    color = "orange",
    method = "gam",
    method.args = list(family = quasibinomial)
  ) +
  labs(
    title = str_wrap(
      "The post-WWII conflict rate still looks elevated compared to pre-WWI when whittling out non-uses of force",
      width = 37
    ),
    subtitle = "Source: Militarized Interstate Confrontations Dataset",
    x = NULL,
    y = "MIC % Rate",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  )
saveit(6, 4, 6)
```
