---
title: "Untitled"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
library(ggrepel)
library(here)
library(countrycode)
library(patchwork)
set_palette(
  qualitative = c(
    "steelblue",
    "orange",
    "navy",
    "red",
    "green3"
  ),
  binary = c("gray30", "red"),
  sequential = c("white", "navy"),
  diverging = c("steelblue", "gray", "red3")
)
source(here::here("_helpers", "splot.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 5, wd = 7) {
  ggsave(
    here::here(
      "110_ai_policy",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data


```{r}
library(googlesheets4)
gs4_deauth()
m26 <- range_speedread("https://docs.google.com/spreadsheets/d/1kyWcrjy73xys1aSlart7njz37WL0BrdLX6tdVin-Nx0/edit?usp=sharing")
m26 <- m26 |> rename_all(tolower) |> 
  filter(finished==1)

m26 |>
  transmute(
    # familiar with AI == 1
    ai_fam = (q27 %in% 1:2) + 0,
    # used AI == 1
    ai_use = ifelse(
        if_all(
          q28_1:q28_6, is.na
      ), 0, 1
    ),
    ## used AI for coding, writing, or summarizing?
    ai_code = ifelse(is.na(q28_5), 0, 1),
    ai_write = ifelse(is.na(q28_3), 0, 1),
    ai_sum = ifelse(is.na(q28_2), 0, 1),
    ai_other = ifelse(
      ai_use == 1 & 
        (ai_code + ai_write + ai_sum) == 0,
      1, 0
    ),
    
    ## AI bad for education?
    ai_bad = ifelse(
      q29_2 %in% 1:2, 1, 0
    )
  ) -> dt
```

## Figures

```{r}
#| fig-height: 5
#| fig-width: 7

dt |>
  summarize(
    across(everything(), ~ mean(.x, na.rm = T))
  ) |>
  pivot_longer(1:6) |>
  mutate(
    ord = n():1,
    lab = c("Are familiar with AI", "Use AI for anything", "...for coding",
            "...for writing", "...for summaries",
            "...for something else")
  ) |>
  ggplot() +
  aes(
    x = value,
    y = reorder(lab, value)
  ) +
  geom_col(
    fill = "red3",
    color = "black"
  ) +
  geom_text(
    aes(label = scales::percent(value)),
    color = "white",
    fontface = "bold",
    hjust = 1.1
  ) +
  scale_x_continuous(
    breaks = NULL
  ) +
  labs(
    title = "Most Students Use AI",
    subtitle = "% of students that:",
    x = NULL,
    y = NULL,
    caption = paste("Source: DU Student Survey Spring 2026 ", logo)
  ) +
  theme(
    panel.grid.major = element_blank()
  )
saveit(1, 5, 7)
```


```{r}
#| fig-height: 5
#| fig-width: 7

dt |>
  pivot_longer(1:6) |>
  group_by(value, name) |>
  mean_ci(ai_bad, ci = .84) |>
  group_by(name) |>
  mutate(
    ord = max(mean)
  ) |>
  ungroup() |>
  mutate(
     lab = rep(
      c("Coding", "Familiar", "Other Use",
        "Summarizing", "Any Use", "Writing"),
      len = 12
    )
  ) |>
  ggplot() +
  aes(
    x = mean,
    y = reorder(lab, ord),
    color = ifelse(value == 0, "Non-users", "Users"),
    xmin = lower,
    xmax = upper
  ) +
  geom_pointrange(
    position = position_dodge(-.5)
  ) +
  geom_text(
    aes(label = scales::percent(mean, 1)),
    vjust = -1,
    fontface = "bold",
    show.legend = F,
    position = position_dodge(-.5)
  ) +
  geom_vline(
    xintercept = .5,
    lty = 2,
    color = "black",
    linewidth = .5
  ) +
  labs(
    title = "AI Users Think AI Undermines Education",
    subtitle = "Share saying AI undermines education by AI use (84% CIs shown)",
    x = NULL,
    y = NULL,
    color = NULL,
    caption = paste("Source: DU Survey Spring 2026", logo)
  ) +
  scale_x_continuous(
    labels = scales::percent,
    breaks = seq(0, 1, by = .1)
  ) +
  theme(
    legend.position = "bottom"
  ) +
  ggpal("binary")
saveit(2, 5, 7)
```
