---
title: "Untitled"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
library(ggrepel)
library(here)
library(countrycode)
library(patchwork)
set_palette(
  qualitative = c(
    "steelblue",
    "orange",
    "navy",
    "red",
    "green3"
  ),
  binary = c("orange3", "navy"),
  sequential = c("white", "navy"),
  diverging = c("steelblue", "gray", "red3")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 5, wd = 7) {
  ggsave(
    here::here(
      "103_fifa",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```

## Data

```{r}
url <- "https://raw.githubusercontent.com/milesdwilliams15/Teaching/main/DPR%20201/Data/world_cup.csv"
dt <- read_csv(url)
```

## Figures

```{r}
#| fig-height: 5
#| fig-width: 7

dt |>
  filter(use == 1) |>
  ggplot() +
  aes(
    x = cutpoint_margin,
    y = post_agg
  ) +
  geom_jitter(
    aes(color = treatment |> as.factor()),
    width = .1,
    height = .1
  ) +
  stat_smooth(
    aes(group = treatment),
    method = "lm",
    formula = y ~1,
    level = .84
  ) +
  geom_vline(
    xintercept = 0,
    lty = 2
  ) +
  scale_y_continuous(
    breaks = 0:8
  ) +
  labs(
    x = NULL,
    y = NULL,
    color = NULL,
    subtitle = "Conflicts started 2 years post-World-Cup by qualifying margin",
    title = "Qualifiers Start More Conflicts",
    caption = logo
  ) +
  ggpal(
    "binary",
    labels = c("Didn't Qualify", "Qualified")
  )
saveit(1)
```

```{r}
dt |>
  filter(use == 1) |>
  group_by(treatment) |>
  mean_ci(post_agg, ci = .84)
```

```{r}
#| fig-height: 5
#| fig-width: 7

dt |>
  filter(use == 1) |>
  ggplot() +
  aes(
    x = cutpoint_margin,
    y = pre_agg
  ) +
  geom_jitter(
    aes(color = treatment |> as.factor()),
    width = .1,
    height = .1
  ) +
  stat_smooth(
    aes(group = treatment),
    method = "lm",
    formula = y ~1,
    level = .84
  ) +
  geom_vline(
    xintercept = 0,
    lty = 2
  ) +
  scale_y_continuous(
    breaks = 0:8
  ) +
  labs(
    x = NULL,
    y = NULL,
    color = NULL,
    subtitle = "Conflicts started 2 years pre-World-Cup by qualifying margin",
    title = "Qualifiers Didn't Start More Conflicts Before",
    caption = logo
  ) +
  ggpal(
    "binary",
    labels = c("Didn't Qualify", "Qualified")
  )
saveit(2)
```


```{r}
dt |>
  filter(use == 1) |>
  group_by(treatment) |>
  mean_ci(pre_agg, ci = .84)
```

```{r}
dt |>
  filter(use == 1) |>
  group_by(treatment) |>
  ct(soccer_popular)
```



```{r}
#| fig-height: 5
#| fig-width: 7
library(estimatr)

bind_rows(
  lm_robust(
    post_agg ~ treatment * I(1 - soccer_popular),
    data = dt |> filter(use == 1),
    se_type = "HC2"
  ) |> 
    tidy() |>
    mutate(model = "Soccer Popular"),
  lm_robust(
    post_agg ~ treatment * soccer_popular,
    data = dt |> filter(use == 1),
    se_type = "HC2"
  ) |> 
    tidy() |>
    mutate(model = "Soccer Not Popular")
) |>
  filter(term == "treatment") |>
  ggplot() +
  aes(
    x = model,
    y = estimate,
    ymin = conf.low,
    ymax = conf.high
  ) +
  geom_pointrange() +
  geom_hline(
    yintercept = 0,
    lty = 2
  ) +
  labs(
    x = NULL,
    y = "Estimate\n(95% CI)",
    subtitle = 
      "Effect of qualifying on conflicts started 2 years post-World-Cup",
    title = 
      "Effect Only Applies Where Soccer is Popular",
    caption = logo
  ) +
  scale_y_continuous(
    breaks = seq(-2, 2, by = .25)
  )
saveit(3)
```



```{r}
dt |>
  filter(use == 1) |>
  group_by(treatment) |>
  ct(democracy)
```


```{r}
#| fig-height: 5
#| fig-width: 7
library(estimatr)

bind_rows(
  lm_robust(
    post_agg ~ treatment * I(1 - democracy),
    data = dt |> filter(use == 1),
    se_type = "HC2"
  ) |> 
    tidy() |>
    mutate(model = "Democracy"),
  lm_robust(
    post_agg ~ treatment * democracy,
    data = dt |> filter(use == 1),
    se_type = "HC2"
  ) |> 
    tidy() |>
    mutate(model = "Not Democracy")
) |>
  filter(term == "treatment") |>
  ggplot() +
  aes(
    x = model,
    y = estimate,
    ymin = conf.low,
    ymax = conf.high
  ) +
  geom_pointrange() +
  geom_hline(
    yintercept = 0,
    lty = 2
  ) +
  labs(
    x = NULL,
    y = "Estimate\n(95% CI)",
    subtitle = 
      "Effect of qualifying on conflicts started 2 years post-World-Cup",
    title = 
      "Effect Only Applies Among Non-Democracies",
    caption = logo
  ) +
  scale_y_continuous(
    breaks = seq(-1, 2, by = 0.25)
  )
saveit(4)
```

