---
title: "Untitled"
format: html
---

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
set_palette(
  qualitative = c(
    "orange3",
    "gray80",
    "navy"
  ),
  binary = c("orange3", "navy"),
  sequential = c("white", "navy"),
  diverging = c("orange3", "white", "navy")
)
source(here::here("my_theme.R"))
saveit <- function(num = 1, ht = 4, wd = 6) {
  ggsave(
    here::here(
      "010_fdi_and_aid",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data

```{r}
library(wbstats)

inds <- c(
  "fdi" = "BM.KLT.DINV.CD.WD",
  "aid" = "DC.ODA.TOTL.CD"
)

dt <- wb_data(
  inds,
  start_date = 1945,
  end_date = 2024
)

## filter out NAs
dt <- drop_na(dt)
```

## Figures

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  group_by(date) |>
  summarize(
    across(fdi:aid, sum)
  ) |>
  pivot_longer(
    -date
  ) |>
  ggplot() +
  aes(x = date, y = value, color = name) +
  geom_point(
    alpha = .4
  ) +
  geom_labelsmooth(
    aes(label = str_to_upper(name)),
    linewidth = 1,
    family = "mono",
    fontface = "bold"
  ) +
  ggpal("binary") +
  my_theme() +
  labs(
    title =
      "Global FDI and Aid, 1970-2022",
    subtitle = 
      "Data Source: World Bank",
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1970, 2020, by = 10)
  ) +
  scale_y_continuous(
    labels = ~ paste0(
      scales::dollar(.x / 1e12),
      " tril"
    )
  ) +
  theme(
    legend.position = ""
  )
saveit(1)
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  filter(
    iso3c == "USA"
  ) |>
  pivot_longer(
    fdi:aid
  ) |>
  ggplot() +
  aes(x = date, y = value, color = name) +
  geom_point(
    alpha = .4
  ) +
  geom_labelsmooth(
    aes(label = str_to_upper(name)),
    linewidth = 1,
    family = "mono",
    fontface = "bold"
  ) +
  ggpal("binary") +
  my_theme() +
  labs(
    title =
      "U.S. FDI and Aid, 1970-2022",
    subtitle = 
      "Data Source: World Bank",
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1970, 2020, by = 10)
  ) +
  scale_y_continuous(
    labels = ~ paste0(
      scales::dollar(.x / 1e09),
      " bil"
    )
  ) +
  theme(
    legend.position = ""
  )
saveit(2)
```

```{r}
#| fig-height: 4
#| fig-width: 6

dt |>
  group_by(date) |>
  summarize(
    fdi_us = sum(fdi[iso3c=="USA"]),
    aid_us = sum(aid[iso3c=="USA"]),
    across(fdi:aid, sum)
  ) |>
  mutate(
    fdi_share = fdi_us / fdi,
    aid_share = aid_us / aid
  ) |>
  pivot_longer(
    fdi_share:aid_share
  ) |>
  mutate(
    name = ifelse(
      name == "fdi_share",
      "FDI",
      "AID"
    )
  ) |>
  ungroup() |>
  filter(
    value > 0
  ) |>
  ggplot() +
  aes(x = date, y = value, color = name) +
  geom_point(
    alpha = .4
  ) +
  geom_labelsmooth(
    aes(label = str_to_upper(name)),
    linewidth = 1,
    family = "mono",
    fontface = "bold"
  ) +
  ggpal("binary") +
  my_theme() +
  labs(
    title =
      "U.S. FDI and Aid Global Share,\n1970-2022",
    subtitle = 
      "Data Source: World Bank",
    caption = logo
  ) +
  scale_x_continuous(
    breaks = seq(1970, 2020, by = 10)
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) +
  theme(
    legend.position = ""
  )
saveit(3)
```

