# Main Analysis Code

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
library(ggrepel)
library(here)
library(countrycode)
library(patchwork)
set_palette(
  qualitative = c(
    "steelblue",
    "orange",
    "navy",
    "red",
    "green3"
  ),
  binary = c("orange3", "navy"),
  sequential = c("white", "navy"),
  diverging = c("steelblue", "gray", "red3")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 4, wd = 6) {
  ggsave(
    here::here(
      "102_world_bank_conditions",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```

## Data

```{r}
read_csv(
  "~/Research Projects/World Bank Post USAID/dfp-conditions-post-usaid/02_data/analysis_data.csv"
) -> dt
```

## Figures

Total disbursements by year:

```{r}
#| fig-height: 5
#| fig-width: 7
dt |>
  group_by(year) |>
  summarize(
    amount = sum(amount)
  ) |>
  ggplot() +
  aes(year, amount / 1e03) +
  geom_col(fill = "gray") +
  labs(
    x = NULL,
    y = NULL,
    subtitle = "Total Disbursements in Billions of $",
    title = "> $278 Billion Disbursed in DFPs Since 2005",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::dollar
  )
saveit(1, 5, 7)
```

Total projects by year:

```{r}
#| fig-height: 5
#| fig-width: 7
dt |>
  group_by(year) |>
  summarize(
    projects = n_distinct(project)
  ) |>
  ggplot() +
  aes(year, projects) +
  geom_col(fill = "gray") +
  labs(
    x = NULL,
    y = NULL,
    subtitle = "Total Projects by Year",
    title = "> 12,000 DFP Projects Since 2005",
    caption = logo
  ) 
saveit(2, 5, 7)
```

Average conditions per project by year:

```{r}
#| fig-height: 5
#| fig-width: 7
dt |>
  group_by(year) |>
  mean_ci(conditions, ci = .84) |>
  ggplot() +
  aes(year, mean, ymin = lower, ymax = upper) +
  geom_col(fill = "gray") +
  geom_errorbar(
    width = .25,
    linewidth = .75
  ) +
  labs(
    x = NULL,
    y = NULL,
    subtitle = "Mean Conditions per Project (84% CIs)",
    title = "Conditions on Financing Trending Down",
    caption = logo
  ) 
saveit(3, 5, 7)
```

Average distance from the US by year:

```{r}
#| fig-height: 5
#| fig-width: 7
dt |>
  group_by(year) |>
  mean_ci(ideal_dist, ci = .84) |>
  ggplot() +
  aes(year, mean, ymin = lower, ymax = upper) +
  geom_col(fill = "gray") +
  geom_errorbar(
    width = .25,
    linewidth = .75
  ) +
  labs(
    x = NULL,
    y = NULL,
    subtitle = "Mean Ideal Point Distance from US (84% CIs)",
    title = "Alignment with US Interests Increasing",
    caption = logo
  ) 
saveit(4, 5, 7)
```

## Model the data

```{r}
library(mgcv)

## Baseline Models
gam(
  amount ~ ideal_dist_lag +
    log(rgdp2015_lag / pop_lag) + log(pop_lag) +
    asinh(aid_lag) +
    s(ccode, bs = "re"),
  family = quasipoisson,
  data = dt
) -> fit1
gam(
  conditions ~ ideal_dist_lag +
    log(rgdp2015_lag / pop_lag) + log(pop_lag) +
    asinh(aid_lag) +
    s(ccode, bs = "re"),
  family = quasipoisson,
  data = dt
) -> fit2

## Including a Time Trend
gam(
  amount ~ ideal_dist_lag +
    log(rgdp2015_lag / pop_lag) + log(pop_lag) +
    asinh(aid_lag) +
    s(ccode, bs = "re") +
    year + I(year^2) + I(year^3),
  family = quasipoisson,
  data = dt
) -> fit3
gam(
  conditions ~ ideal_dist_lag +
    log(rgdp2015_lag / pop_lag) + log(pop_lag) +
    asinh(aid_lag) +
    s(ccode, bs = "re") +
    year + I(year^2) + I(year^3),
  family = quasipoisson,
  data = dt
) -> fit4
```

Prep the models for visualization:

```{r}
1:4 |>
  map_dfr(
    ~ ggregtab::tidy_coeftest(
      list(fit1, fit2, fit3, fit4)[[.x]],
      model = .x
    )
  ) |>
  filter(
    !str_detect(term, "ccode")
  ) |>
  mutate(
    model = case_when(
      model == 1 ~ "(1)\nDisbursed",
      model == 2 ~ "(2)\nConditions",
      model == 3 ~ "(3)\nDisbursed",
      model == 4 ~ "(4)\nConditions"
    )
  ) -> model_out
```

A coefficient plot:

```{r}
#| fig-height: 5
#| fig-width: 7

model_out |>
  filter(term == "ideal_dist_lag") |>
  mutate(
    across(
      c(estimate, conf.low, conf.high),
      ~ exp(.x) - 1
    ),
    type = rep(
      c("(A) No Adjusting for Time Trend", "(B) Adjusting for Time Trend"),
      each = 2
    )
  ) |>
  ggplot() +
  aes(
    x = model,
    y = estimate,
    ymin = conf.low,
    ymax = conf.high
  ) +
  facet_wrap(~ type, scales = "free_x") +
  geom_pointrange() +
  geom_hline(
    yintercept = 0,
    lty = 2
  ) +
  labs(
    x = "Estimates from PPML Models",
    y = NULL,
    subtitle = "% change predicted by moving 1 standard deviation away from the US ideal point",
    title = "Secular Trends Erase Conditionality Effect",
    caption = logo
  ) +
  scale_y_continuous(
    labels = scales::percent
  ) 
saveit(5)
```


