---
title: "War and Negotiated Settlement"
format: html
---

## Setup

```{r packages + settings}
library(tidyverse)
library(socsci)
library(geomtextpath)
library(coolorrr)
library(here)
set_palette(
  qualitative = c(
    "steelblue",
    "navy",
    "red3",
    "orange3"
  ),
  binary = c("orange3", "navy"),
  sequential = c("skyblue1", "navy"),
  diverging = c("red3", "white", "navy")
)
source(here::here("my_theme.R"))
theme_set(my_theme())
saveit <- function(num = 1, ht = 4, wd = 6) {
  ggsave(
    here(
      "033_war_negotiation",
      paste0("fig", num, ".png")
    ),
    height = ht,
    width = wd,
    dpi = 500
  )
}
```


## Data

```{r}
mie <- read_csv(
  here(
    "_data",
    "mie-1.0.csv"
  )
)
mic <- read_csv(
  here(
    "_data",
    "mic-conf-1.0.csv"
  )
)
micend <- read_csv(
  here(
    "_data",
    "micend-1.0.csv"
  )
)
dt <- left_join(
  mie |> select(micnum, ccode1, ccode2, styear),
  micend |>
    select(-c(endmonth, endday))
)
dt |> 
  drop_na(endyear) -> dt
```

```{r}
dt |>
  mutate(
    c1 = pmin(ccode1, ccode2),
    c2 = pmax(ccode1, ccode2),
    c1 = countrycode::countrycode(
      c1, "cown", "country.name"
    ),
    c2 = countrycode::countrycode(
      c2, "cown", "country.name"
    ),
    dyad = paste0(c1, "-", c2),
    outcome = frcode(
      endingmethod == 0 ~ "No agreement",
      endingmethod %in% 1:3 ~ 
        "Written agreement",
      endingmethod %in% c(4, 6:7) ~
        "3rd Party Resolution",
      endingmethod == 8 ~ "Withdrawl",
      TRUE ~ "Other"
    ),
    written = ifelse(
      outcome == "Written agreement",
      1, 0
    ),
    mediation = ifelse(
      global == 1 |
        state == 1 |
        regional == 1 |
        nonstate == 1,
      1, 0
    )
  ) |>
  select(-c(ccode1, ccode2, c1, c2)) |>
  group_by(micnum, dyad) |>
  summarize(
    styear = min(styear),
    endyear = max(endyear),
    across(
      everything(),
      unique
    )
  ) -> sdt
```

```{r}
sdt |>
  arrange(dyad, styear) |> 
  group_by(dyad) |>
  mutate(
    time = lead(styear, order_by = styear) - endyear
  ) |>
  ungroup() -> sdt
```


## Figures

```{r}
#| fig-height: 4
#| fig-width: 6

sdt |>
  distinct(micnum, endyear, written) |>
  group_by(endyear) |>
  mean_ci(written) |>
  ggplot() +
  aes(endyear, mean) +
  geom_line(color = "orange3") +
  geom_smooth(se = F, color = "navy") +
  labs(
    title = str_wrap(
      "Share of conflicts that end by written settlement",
      width = 37
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_y_continuous(
    labels = percent
  )
saveit(1)
```

```{r}
#| fig-height: 4
#| fig-width: 6

sdt |>
  distinct(micnum, endyear, mediation) |>
  group_by(endyear) |>
  mean_ci(mediation) |>
  ggplot() +
  aes(endyear, mean) +
  geom_line(color = "orange3") +
  geom_smooth(se = F, color = "navy") +
  labs(
    title = str_wrap(
      "Share of conflicts that involve a third-party mediator",
      width = 37
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_y_continuous(
    labels = percent
  )
saveit(2)
```

```{r}
#| fig-height: 4
#| fig-width: 6

sdt |>
  mutate(
    outcome = case_when(
      mediation == 1 & written == 1 ~ 
        "Mediation\n+ Written Agreement",
      mediation == 1 & written == 0 ~
        "Mediation\n+ No Written Agreement",
      mediation == 0 & written == 1 ~
        "No Mediation\n+ Written Agreement",
      mediation == 0 & written == 0 ~ 
        "No Mediation\n+ No Written Agreement"
    )
  ) |>
  ggplot() +
  aes(ifelse(!is.na(time), 1, 0), outcome) +
  stat_summary(
    fun.data = mean_cl_boot,
    color = "navy"
  ) +
  labs(
    title = str_wrap(
      "How often do countries fight again?",
      width = 37
    ),
    subtitle = str_wrap(
      "Share (%) of the time a pair of countries fight again based on previous conflict outcome (bootstrapped 95% confidence intervals shown)",
      width = 55
    ),
    x = NULL,
    y = NULL,
    caption = logo
  ) +
  scale_x_continuous(
    n.breaks = 10,
    labels = percent
  )
saveit(3)
```
